import './globals.css'

export const metadata = {
  title: 'Rafa',
  description: 'Generated by Next.js',
  icons: {
    icon: '/tora-orange.png',
  },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
